Revert "NODE_MODULE_INIT"
This reverts commit 20652f9171900613c4f809f27027001fc09f817a.
Original change broke node-zstd when it is imported, with the error

```
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
```